/**
 * Genesis Types (Edge Function Version)
 *
 * Shared types for AI-powered world generation in Architect mode.
 * This is a mirror of @mythos/core/genesis/types.ts for edge functions
 * which cannot import npm packages directly.
 *
 * NOTE: Keep in sync with packages/core/src/genesis/types.ts
 */

/**
 * An entity generated by the genesis AI during world scaffolding.
 * Represents characters, locations, items, factions, or magic systems.
 */
export interface GeneratedEntity {
  name: string;
  type: "character" | "location" | "item" | "faction" | "magic_system";
  description: string;
  properties?: Record<string, string | number | boolean>;
  relationships?: Array<{
    targetName: string;
    type: string;
    description?: string;
  }>;
}

/**
 * An outline section generated during world scaffolding.
 */
export interface GenesisOutlineSection {
  title: string;
  summary: string;
}

/**
 * Full response from the genesis AI.
 */
export interface GenesisResult {
  entities: GeneratedEntity[];
  worldSummary: string;
  suggestedTitle?: string;
  outline?: GenesisOutlineSection[];
}
