export const MAX_DECISION_LENGTH = 10000;
export const MAX_DECISION_EMBEDDING_CHARS = 8000;

export {
  QDRANT_IMAGE_VECTOR,
  QDRANT_SPARSE_VECTOR,
  QDRANT_TEXT_VECTOR,
  SAGA_IMAGES_COLLECTION_LEGACY,
  SAGA_UNIFIED_COLLECTION,
  SAGA_VECTORS_COLLECTION_LEGACY,
} from "../../lib/qdrantCollections";
