/**
 * Genesis Types
 *
 * Shared types for AI-powered world generation in Architect mode.
 * Used by both the ai-genesis edge function and the web client.
 */

/**
 * An entity generated by the genesis AI during world scaffolding.
 * Represents characters, locations, items, factions, or magic systems.
 */
export interface GeneratedEntity {
  name: string;
  type: "character" | "location" | "item" | "faction" | "magic_system";
  description: string;
  properties?: Record<string, string | number | boolean>;
  relationships?: Array<{
    targetName: string;
    type: string;
    description?: string;
  }>;
}

/**
 * An outline section generated during world scaffolding.
 */
export interface GenesisOutlineSection {
  title: string;
  summary: string;
}

/**
 * Full response from the genesis AI.
 */
export interface GenesisResult {
  entities: GeneratedEntity[];
  worldSummary: string;
  suggestedTitle?: string;
  outline?: GenesisOutlineSection[];
}
